name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    environment:
      name: 'production-backend'
      url: 'https://project-giveback.azurewebsites.net'
    name: Build and Deploy
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Backend (Node.js) Build and Test
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'
      
      - name: Install Backend Dependencies
        working-directory: server
        run: npm install
        
      # Frontend (React.js) Build and Test
      - name: Install Frontend Dependencies
        working-directory: giveback-frontend-manager
        run: npm install
        
      - name: Build Frontend
        working-directory: giveback-frontend-manager
        run: npm run build
      
      # Deploy Backend (e.g., to Azure App Service)
      - name: Deploy Backend
        uses: Azure/webapps-deploy@v2
        with:
          app-name: 'Project-GiveBack'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_BACKEND }}
          package: ./server  # Corrected package path

      # Deploy Frontend (e.g., to Azure Storage Static Website)
      - name: Deploy Frontend
        uses: Azure/webapps-deploy@v2
        with:
          app-name: 'GiveBack'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_FRONTEND }}
          package: ./giveback-frontend-manager/dist  # Corrected package path
